ALTER TABLE orders ADD COLUMN items_subtotal_cents INT NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN service_fee_cents INT NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN delivery_fee_cents INT NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN discount_cents INT NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN tip_cents INT NOT NULL DEFAULT 0;
